import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['import', 'promise', 'unicorn'],
  categories: {
    correctness: 'error',
  },
  env: {
    builtin: true,
    es2026: true,
  },
  options: {
    reportUnusedDisableDirectives: 'error',
  },
  rules: {
    'array-callback-return': 'error',
    'default-case': ['error', { commentPattern: '^no default$' }],
    'default-case-last': 'error',
    eqeqeq: ['error', 'smart'],
    'no-array-constructor': 'error',
    'no-await-in-loop': 'error',
    'no-case-declarations': 'error',
    'no-cond-assign': ['error', 'except-parens'],
    'no-constructor-return': 'error',
    'no-empty': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'error',
    'no-label-var': 'error',
    'no-labels': ['error', { allowLoop: true, allowSwitch: false }],
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-object-constructor': 'error',
    'no-promise-executor-return': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-return-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-template-curly-in-string': 'error',
    'no-throw-literal': 'error',
    'no-undef': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable': 'error',
    'no-use-before-define': [
      'error',
      { functions: false, classes: false, variables: false },
    ],
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'prefer-object-has-own': 'error',
    'unicode-bom': 'error',

    'import-x/default': 'error',
    'import-x/export': 'error',
    'import-x/extensions': ['error', { js: 'never', json: 'always' }],
    'import-x/named': 'error',
    'import-x/namespace': ['error', { allowComputed: true }],
    'import-x/no-absolute-path': 'error',
    'import-x/no-amd': 'error',
    'import-x/no-commonjs': 'error',
    'import-x/no-cycle': 'error',
    'import-x/no-duplicates': 'error',
    'import-x/no-empty-named-blocks': 'error',
    'import-x/no-mutable-exports': 'error',
    'import-x/no-named-as-default': 'error',
    'import-x/no-named-as-default-member': 'error',
    'import-x/no-self-import': 'error',

    'promise/always-return': 'error',
    'promise/catch-or-return': 'error',
    'promise/no-callback-in-promise': 'warn',
    'promise/no-nesting': 'warn',
    'promise/no-new-statics': 'error',
    'promise/no-promise-in-callback': 'warn',
    'promise/no-return-in-finally': 'warn',
    'promise/no-return-wrap': 'error',
    'promise/param-names': 'error',
    'promise/valid-params': 'warn',

    'unicorn/error-message': 'error',
    'unicorn/no-abusive-eslint-disable': 'error',
    'unicorn/no-instanceof-array': 'error',
    'unicorn/no-negation-in-equality-check': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/throw-new-error': 'error',
  },
  overrides: [
    {
      files: ['**/*.{mjs,mts}'],
      rules: {
        'import-x/extensions': ['error', 'ignorePackages'],
      },
    },
    {
      files: ['**/*.{ts,mts,tsx}'],
      plugins: ['typescript'],
      rules: {
        'constructor-super': 'off',
        'default-case': 'off',
        'no-class-assign': 'off',
        'no-const-assign': 'off',
        'no-dupe-class-members': 'off',
        'no-dupe-keys': 'off',
        'no-func-assign': 'off',
        'no-import-assign': 'off',
        'no-new-native-nonconstructor': 'off',
        'no-obj-calls': 'off',
        'no-redeclare': 'off',
        'no-setter-return': 'off',
        'no-this-before-super': 'off',
        'no-undef': 'off',
        'no-unreachable': 'off',
        'no-unsafe-negation': 'off',
        'no-unused-vars': [
          'error',
          {
            vars: 'all',
            args: 'after-used',
            caughtErrors: 'none',
            argsIgnorePattern: '^_',
          },
        ],
        'no-use-before-define': [
          'error',
          {
            functions: false,
            classes: false,
            variables: false,
            typedefs: false,
          },
        ],
        'no-var': 'error',
        'no-with': 'off',
        'prefer-const': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',

        '@typescript-eslint/adjacent-overload-signatures': 'error',
        '@typescript-eslint/array-type': 'error',
        '@typescript-eslint/ban-ts-comment': 'error',
        '@typescript-eslint/consistent-type-assertions': [
          'error',
          { assertionStyle: 'as' },
        ],
        '@typescript-eslint/consistent-type-imports': 'error',
        '@typescript-eslint/no-confusing-non-null-assertion': 'error',
        '@typescript-eslint/no-dynamic-delete': 'error',
        '@typescript-eslint/no-empty-interface': [
          'error',
          { allowSingleExtends: true },
        ],
        '@typescript-eslint/no-empty-object-type': 'error',
        '@typescript-eslint/no-explicit-any': 'error',
        '@typescript-eslint/no-extraneous-class': 'error',
        '@typescript-eslint/no-namespace': 'error',
        '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
        '@typescript-eslint/no-require-imports': 'error',
        '@typescript-eslint/no-unnecessary-type-constraint': 'error',
        '@typescript-eslint/no-unsafe-function-type': 'error',
        '@typescript-eslint/prefer-for-of': 'error',
        '@typescript-eslint/prefer-function-type': 'error',
        '@typescript-eslint/prefer-optional-chain': 'error',
        '@typescript-eslint/unified-signatures': 'error',

        'import-x/named': 'off',
      },
    },
    {
      files: [
        '**/*.config.{ts,mts,js,cjs,mjs}',
        '**/.*rc.{ts,mts,js,cjs,mjs}',
      ],
      rules: {
        'import-x/no-default-export': 'off',
      },
      env: {
        node: true,
      },
    },
    {
      files: ['**/*.config.{js,cjs}', '**/.*rc.{js,cjs}'],
      rules: {
        'import-x/no-commonjs': 'off',
      },
      env: {
        node: true,
      },
    },
  ],
});
