import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['typescript'],
  options: {
    typeAware: true,
  },
  overrides: [
    {
      files: ['**/*.{ts,mts,tsx}'],
      rules: {
        'no-throw-literal': 'off',
        'prefer-promise-reject-errors': 'off',
        'require-await': 'off',

        'typescript/await-thenable': 'error',
        'typescript/consistent-type-exports': 'error',
        'typescript/no-array-delete': 'error',
        'typescript/no-base-to-string': 'off',
        'typescript/no-confusing-void-expression': 'error',
        'typescript/no-deprecated': 'error',
        'typescript/no-duplicate-type-constituents': 'error',
        'typescript/no-floating-promises': 'error',
        'typescript/no-for-in-array': 'error',
        'typescript/no-implied-eval': 'error',
        'typescript/no-meaningless-void-operator': 'error',
        'typescript/no-misused-promises': 'error',
        'typescript/no-misused-spread': 'error',
        'typescript/no-mixed-enums': 'error',
        'typescript/no-redundant-type-constituents': 'error',
        'typescript/no-unnecessary-boolean-literal-compare': 'error',
        'typescript/no-unnecessary-condition': [
          'error',
          { allowConstantLoopConditions: 'only-allowed-literals' },
        ],
        'typescript/no-unnecessary-template-expression': 'error',
        'typescript/no-unnecessary-type-arguments': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-conversion': 'error',
        'typescript/no-unnecessary-type-parameters': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/no-unsafe-type-assertion': 'error',
        'typescript/no-unsafe-unary-minus': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-find': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/prefer-reduce-type-parameter': 'error',
        'typescript/prefer-return-this-type': 'error',
        'typescript/promise-function-async': 'error',
        'typescript/related-getter-setter-pairs': 'error',
        'typescript/require-array-sort-compare': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': [
          'error',
          {
            allowAny: false,
            allowBoolean: false,
            allowNullish: false,
            allowNumberAndString: false,
            allowRegExp: false,
          },
        ],
        'typescript/restrict-template-expressions': [
          'error',
          {
            allowAny: false,
            allowBoolean: false,
            allowNever: false,
            allowNullish: false,
            allowNumber: false,
            allowRegExp: false,
          },
        ],
        'typescript/return-await': [
          'error',
          'error-handling-correctness-only',
        ],
        'typescript/strict-boolean-expressions': 'error',
        'typescript/switch-exhaustiveness-check': 'error',
        'typescript/unbound-method': 'error',
        'typescript/use-unknown-in-catch-callback-variable': 'error',
      },
    },
  ],
});
